openapi: 3.0.3
info:
  title: Resume Backend Service API
  version: 1.0.0
  description: API para procesamiento asíncrono de CVs y recepción de resultados procesados.

servers:
  - url: http://localhost:8080/api/v1
    description: Servidor local de desarrollo

paths:
  /health/:
    get:
      summary: Health Check
      description: Verifica que el servicio esté funcionando correctamente.
      tags:
        - Health
      responses:
        '200':
          description: Servicio funcionando correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: resume-backend-service

  /resume/:
    post:
      summary: Enviar CV para procesamiento asíncrono
      description: >
        Recibe un archivo de CV (PDF, TXT, DOC, o DOCX) junto con instrucciones opcionales
        y un idioma objetivo. Encola la solicitud para procesamiento asíncrono y retorna
        una confirmación 202 Accepted.
      tags:
        - Resume Processing
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: |
                    Archivo de CV a procesar.

                    **Formatos permitidos:** .pdf, .txt, .docx

                    **Tamaño máximo:** 10 MB

                    **Nota:** El formato .doc (antiguo) no está soportado.
                instructions:
                  type: string
                  description: Instrucciones específicas para el procesamiento del CV (opcional)
                  example: "Extraer experiencia laboral de los últimos 5 años"
                language:
                  type: string
                  description: Idioma del CV o idioma deseado para el procesamiento
                  default: es
                  example: es
              required:
                - file
      responses:
        '202':
          description: Solicitud aceptada y encolada para procesamiento
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: accepted
                  message:
                    type: string
                    example: Solicitud encolada para procesamiento.
        '400':
          description: Petición inválida
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: "Campo 'file' requerido."
              examples:
                missing_file:
                  summary: Archivo no proporcionado
                  value:
                    status: error
                    message: "Campo 'file' requerido."
                invalid_format:
                  summary: Formato de archivo no permitido
                  value:
                    status: error
                    message: "Formato de archivo no permitido. Permite: .pdf, .txt, .docx"
        '500':
          description: Error interno del servidor

  /resume/my-resumes:
    get:
      summary: Obtener listado de CVs del usuario
      description: Retorna un listado resumido de todos los CVs procesados por el usuario autenticado
      tags:
        - Resume Processing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Listado de CVs obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeListResponse'
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Usuario no autenticado

  /resume/{request_id}:
    get:
      summary: Obtener detalle completo de un CV
      description: Retorna toda la información de un CV procesado incluyendo datos estructurados
      tags:
        - Resume Processing
      security:
        - bearerAuth: []
      parameters:
        - name: request_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID único de la solicitud de procesamiento
      responses:
        '200':
          description: Detalle del CV obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeDetail'
        '400':
          description: Request ID inválido
        '401':
          description: No autenticado
        '403':
          description: No tienes permiso para ver este CV
        '404':
          description: CV no encontrado

  /resume/results:
    post:
      summary: Recibir resultados de CV procesado (Webhook/Callback)
      description: >
        Endpoint para recibir los datos procesados del CV desde AWS Lambda.
        Recibe un JSON con metadata del procesamiento y los datos estructurados del CV.
      tags:
        - Resume Processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AWSLambdaResponse'
      responses:
        '200':
          description: Datos procesados correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Datos procesados correctamente.
        '400':
          description: Error al parsear el cuerpo de la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Error al parsear el cuerpo de la solicitud.

components:
  schemas:
    AWSLambdaResponse:
      type: object
      description: Respuesta completa de AWS Lambda con metadata y datos procesados
      properties:
        input_file:
          type: string
          description: Ruta S3 del archivo de entrada
          example: "s3://cv-processor-dev/inputs/2025-11-29/05-05-08/cv-clean.pdf"
        output_file:
          type: string
          description: Ruta S3 del archivo de salida JSON
          example: "s3://cv-processor-dev/outputs/2025-11-29/05-05-08/cv-clean.json"
        processing_time_ms:
          type: integer
          description: Tiempo de procesamiento en milisegundos
          example: 11919
        status:
          type: string
          description: Estado del procesamiento
          enum: [success, error]
          example: success
        structured_data:
          $ref: '#/components/schemas/CVProcessedData'
      required:
        - input_file
        - output_file
        - status
        - structured_data

    CVProcessedData:
      type: object
      description: Estructura completa de datos procesados del CV
      properties:
        certifications:
          type: array
          items:
            $ref: '#/components/schemas/Certification'
        education:
          type: array
          items:
            $ref: '#/components/schemas/Education'
        header:
          $ref: '#/components/schemas/Header'
        professionalExperience:
          type: array
          items:
            $ref: '#/components/schemas/Experience'
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
        technicalSkills:
          $ref: '#/components/schemas/TechnicalSkills'
      example:
        header:
          name: "Juan Pérez"
          contact:
            email: "juan.perez@example.com"
            phone: "+34 600 123 456"
        professionalExperience:
          - company: "Tech Corp"
            position: "Senior Developer"
            period:
              start: "2020-01"
              end: "2023-12"
            responsibilities:
              - "Desarrollo de aplicaciones web"
              - "Liderazgo de equipo técnico"
        education:
          - institution: "Universidad de Madrid"
            degree: "Ingeniería en Informática"
            graduationDate: "2019-06"
        technicalSkills:
          skills:
            - "JavaScript"
            - "React"
            - "Node.js"
        certifications:
          - name: "AWS Certified Developer"
            dateObtained: "2021-03"
        projects:
          - name: "E-commerce Platform"
            description: "Plataforma de comercio electrónico escalable"
            technologies:
              - "React"
              - "Node.js"
              - "MongoDB"

    Certification:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la certificación
        dateObtained:
          type: string
          description: Fecha de obtención (formato flexible)

    Education:
      type: object
      properties:
        institution:
          type: string
          description: Nombre de la institución educativa
        degree:
          type: string
          description: Título o grado obtenido
        graduationDate:
          type: string
          description: Fecha de graduación
        achievements:
          type: array
          items:
            type: string
          description: Logros académicos (opcional)

    Header:
      type: object
      properties:
        name:
          type: string
          description: Nombre completo de la persona
        contact:
          $ref: '#/components/schemas/Contact'

    Contact:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Correo electrónico
        phone:
          type: string
          description: Número de teléfono

    Experience:
      type: object
      properties:
        company:
          type: string
          description: Nombre de la empresa
        position:
          type: string
          description: Cargo o posición ocupada
        period:
          $ref: '#/components/schemas/Period'
        responsibilities:
          type: array
          items:
            type: string
          description: Lista de responsabilidades

    Period:
      type: object
      properties:
        start:
          type: string
          description: Fecha de inicio (formato flexible)
        end:
          type: string
          description: Fecha de fin (formato flexible, puede ser "Presente")

    Project:
      type: object
      properties:
        name:
          type: string
          description: Nombre del proyecto
        description:
          type: string
          description: Descripción del proyecto
        technologies:
          type: array
          items:
            type: string
          description: Tecnologías utilizadas

    TechnicalSkills:
      type: object
      properties:
        skills:
          type: array
          items:
            type: string
          description: Lista de habilidades técnicas

    ResumeListResponse:
      type: object
      description: Respuesta con listado de CVs del usuario
      properties:
        total:
          type: integer
          description: Número total de CVs
          example: 2
        resumes:
          type: array
          items:
            $ref: '#/components/schemas/ResumeListItem'

    ResumeListItem:
      type: object
      description: Item resumido de un CV en el listado
      properties:
        request_id:
          type: string
          format: uuid
          description: ID único de la solicitud
        original_filename:
          type: string
          description: Nombre del archivo original
          example: "cv.pdf"
        status:
          type: string
          enum: [pending, uploaded, processing, completed, failed]
          description: Estado del procesamiento
        created_at:
          type: string
          format: date-time
          description: Fecha de creación
        completed_at:
          type: string
          format: date-time
          description: Fecha de completado (si aplica)
        full_name:
          type: string
          description: Nombre extraído del CV (si está completado)
          example: "Andres Sepulveda"
        email:
          type: string
          format: email
          description: Email extraído del CV (si está completado)
          example: "andressep.95@gmail.com"

    ResumeDetail:
      type: object
      description: Detalle completo de un CV procesado
      properties:
        request_id:
          type: string
          format: uuid
        original_filename:
          type: string
        original_file_type:
          type: string
          example: ".pdf"
        file_size_bytes:
          type: integer
          example: 3471
        language:
          type: string
          example: "es"
        instructions:
          type: string
        status:
          type: string
          enum: [pending, uploaded, processing, completed, failed]
        s3_input_url:
          type: string
        s3_output_url:
          type: string
        processing_time_ms:
          type: integer
        error_message:
          type: string
        created_at:
          type: string
          format: date-time
        uploaded_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        structured_data:
          $ref: '#/components/schemas/CVProcessedData'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token JWT obtenido del servicio de autenticación
