openapi: 3.0.3
info:
  title: CV Processor API
  version: 1.0.0
  description: API para procesar archivos de CV junto con instrucciones y lenguaje.

paths:
  /process:
    post:
      summary: Envía un CV para procesamiento asíncrono.
      description: >
        Este endpoint recibe un archivo de CV (PDF, TXT, DOC, o DOCX) junto con una cadena 
        de instrucciones y un idioma objetivo. Retorna una confirmación 202 Accepted, 
        indicando que la solicitud ha sido encolada para procesamiento posterior.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: >
                    Archivo a procesar. Formatos permitidos: **PDF, TXT, DOC, DOCX**.
                  # Puedes añadir un ejemplo de tipo MIME, aunque esto es solo informativo
                  # content:
                  #   application/pdf: {}
                  #   text/plain: {}
                instructions:
                  type: string
                  description: Indicaciones para el procesamiento del archivo
                language:
                  type: string
                  description: Idioma solicitado para la salida
              required:
                - file

      responses:
        '202':
          description: Solicitud ACEPTADA para procesamiento (Asíncrono)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: accepted
                  message:
                    type: string
                    example: La solicitud ha sido encolada para procesamiento.
                  # Opcionalmente, puedes devolver un Job ID o una URI de estado:
                  # jobId:
                  #   type: string
                  #   format: uuid
                  #   example: 123e4567-e89b-12d3-a456-426614174000
        '400':
          description: Petición inválida (ej. archivo no soportado, campos faltantes)
        '500':
          description: Error interno del servidor